name = "battleships-ws"
main = "worker/dist/index.js"
compatibility_date = "2025-09-03"

[[durable_objects.bindings]]
name = "GAME_ROOMS"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]